all:
  children:
    laptops:
      vars:
        ansible_user: hasan
      hosts:
        lenovo-1:
          wifi_interface: wlp2s0
        lenovo-2:
          wifi_interface: wlp0s20f3
        thinkpad-1:
          wifi_interface: wlp4s0
